---
title: "pstat 175 final project"
author: "alek lichucki"
date: "11/15/2019"
output: html_document
---

cleaning up the data
```{r}
player_data = read.csv("player_data.csv")
work_data = player_data
work_data = na.omit(work_data) #getting rid of columns with missing values
for (i in 1:4544) {
  work_data$years_played[i] = work_data$year_end[i] - work_data$year_start[i] + 1#this is to find the number of yers played 
  if (work_data$year_end[i] == 2018){ #censoring is done based off of if they are a current player or not year 2018 because this is when the data was last updated
    work_data$cens[i] = 0
  }
  else{
    work_data$cens[i] = 1
  }
}
for (i in 1:4544) { #making a column to show the decade when the player started
  if (work_data$year_start[i] >= 1940 & work_data$year_start[i] < 1950){
    work_data$dec_start[i] = 1940
  }
  else if ((work_data$year_start[i] >= 1950 & work_data$year_start[i] < 1960)){
    work_data$dec_start[i] = 1950
  }
  else if ((work_data$year_start[i] >= 1960 & work_data$year_start[i] < 1970)){
    work_data$dec_start[i] = 1960
  }
  else if ((work_data$year_start[i] >= 1970 & work_data$year_start[i] < 1980)){
    work_data$dec_start[i] = 1970
  }
  else if ((work_data$year_start[i] >= 1980 & work_data$year_start[i] < 1990)){
    work_data$dec_start[i] = 1980
  }
  else if ((work_data$year_start[i] >= 1990 & work_data$year_start[i] < 2000)){
    work_data$dec_start[i] = 1990
  }
  else if ((work_data$year_start[i] >= 2000 & work_data$year_start[i] < 2010)){
    work_data$dec_start[i] = 2000
  }
  else if ((work_data$year_start[i] >= 2010 & work_data$year_start[i] < 2020)){
    work_data$dec_start[i] = 2010
  }
}

for (i in 1:4544) { #this is to convert the height to inches rather than height being a factor
  work_data$height_str[i] = toString(work_data$height[i])
  x = unlist(strsplit(work_data$height_str[i], split = "-"))
  work_data$height_inches[i] = as.integer(x[1])*12 + as.integer(x[2])
}


#this one also throws an error probably due to missing values FIX
for(i in 1:4544){ #making weight groups to make analysis easier
  if (work_data$weight[i] < 175){
    work_data$weight_group[i] = 0
  }
  else if (work_data$weight[i] >= 175 & work_data$weight[i] < 225){
    work_data$weight_group[i] = 1
  }
  else if (work_data$weight[i] >= 225){
    work_data$weight_group[i] = 2
  }
}

#this one throws an error for some reason but still works??????
for (i in 1:4544){ #making height groups to make analysis more manageable
  if (work_data$height_inches[i] < 72){
    work_data$height_group[i] = 0
  }
  else if (work_data$height_inches[i] >= 72 & work_data$height_inches[i] < 84){
    work_data$height_group[i] = 1
  }
  else if (work_data$height_inches[i] >= 84){
    work_data$height_group[i] = 2
  }
}

work_data
```


doing kaplan meier curves
```{r}
library(survival)
kap_time = work_data$years_played
kap_cens = work_data$cens
kap_surv = Surv(kap_time, kap_cens)
kap_fit = survfit(kap_surv ~ 1) #this is the kaplan meier fit general
#summary(kap_fit)
plot(kap_fit, main = "Survival Probability for Players Career", xlab = "Years", ylab = "Survival Prob")

#doing kaplan meier for decade
kap_fit_dec = survfit(kap_surv ~ work_data$dec_start)
#summary(kap_fit_dec)
plot(kap_fit_dec, col = c(1, 2, 3, 4, 5, 6, 7, 8), main = "Survival Probability for Players Career Against Decade Started", ylab = "Survival Prob", xlab = "Years")
legend("topright",legend=c("1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"), col=c(1, 2, 3, 4, 5, 6, 7, 8),pch=rep(19,2))
#kap meier for height groups
kap_fit_height = survfit(kap_surv ~ work_data$height_group)
#summary(kap_fit_height)
plot(kap_fit_height, col = c(1, 2, 3), main = "Survival Probability for Players Career Against Height", ylab = "Survival Prob", xlab = "Years")
legend("topright", legend = c("Less Than 6 Ft", "6 Ft - 7 Ft", "7 Ft Plus"), col = c(1, 2, 3), pch=rep(19,2))
#kap meier for weight groups
kap_fit_weight = survfit(kap_surv ~ work_data$weight_group)
#summary(kap_fit_weight)
plot(kap_fit_weight, col = c(1, 2, 3), main = "Survival Probability for Players Career Against Weight", ylab = "Survival Prob", xlab = "Years")
legend("topright", legend = c("Less Than 175", "175-225", "Greater Than 225"), col = c(1, 2, 3), pch=rep(19,2))
```

performing the log rank test
```{r}
survdiff(kap_surv ~ work_data$dec_start) #test says there is a statistically significant difference between the predictors
survdiff(kap_surv ~ work_data$height_group) #stat sig differnce between the predictors-
survdiff(kap_surv ~ work_data$weight_group) #stat sig diff btwn predictors
```

model building, make a full model with all the covariates
```{r}
model_full = coxph(kap_surv ~ work_data$dec_start + work_data$height_group + work_data$weight_group)
step(model_full, direction = "backward")
anova(model_full)
```

checking cox ph model assumptions
```{r}
cox.zph(model_full) #all the pvals are above .05 so they dont violate the assumptions, dont have to work with a model that odesnt follow the cox ph assumptions
#cloglog for decade started, slight crossing but we are going to look at the output of cox zph over this
plot(survfit(Surv(kap_time, kap_cens)~work_data$dec_start), fun = "cloglog", col = 1:8, main = "Cloglog for Decade Started", lwd = 2)
legend("topright",legend=c("1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"), col=c(1, 2, 3, 4, 5, 6, 7, 8),pch=rep(19,2))
#cloglog for weight group, parallel and not converging or diverging
plot(survfit(Surv(kap_time, kap_cens)~work_data$weight_group), fun = "cloglog", col = 1:3, main = "Cloglog for Weight Group", lwd = 2)
legend("topright", legend = c("Less Than 175", "175-225", "Greater Than 225"), col = c(1, 2, 3), pch=rep(19,2))
#cloglog for height group, parallel and not converging or diverging
plot(survfit(Surv(kap_time, kap_cens)~work_data$height_group), fun = "cloglog", col = 1:8, main = "Cloglog for Height Group", lwd = 2)
legend("topright", legend = c("Less Than 6 Ft", "6 Ft - 7 Ft", "7 Ft Plus"), col = c(1, 2, 3), pch=rep(19,2))
```

checking to see if there are interaction terms (dec_start*height_group, dec_start*weight_group, height_group*weight_group)
```{r}
#checking the interaction between dec_start and height_group, interaction
additive.model = coxph(Surv(kap_time,kap_cens)~ work_data$dec_start + work_data$height_group)
interaction.model = coxph(Surv(kap_time,kap_cens)~ work_data$dec_start * work_data$height_group)
LRT <- 2*(logLik(interaction.model) - logLik(additive.model))
LRT
round(pchisq(as.numeric(LRT), 2, lower.tail = FALSE),3)
#checking interaction between dec_start and weight_group, gives a 0 so going to not include this as an interaction term idk if this is correct
additive.model = coxph(Surv(kap_time,kap_cens)~ work_data$dec_start + work_data$weight_group)
interaction.model = coxph(Surv(kap_time,kap_cens)~ work_data$dec_start * work_data$weight_group)
LRT <- 2*(logLik(interaction.model) - logLik(additive.model))
LRT
round(pchisq(as.numeric(LRT), 2, lower.tail = FALSE),3)
#checking the interaction between height_group and weight_group, no interaction
additive.model = coxph(Surv(kap_time,kap_cens)~ work_data$height_group + work_data$weight_group)
interaction.model = coxph(Surv(kap_time,kap_cens)~ work_data$height_group * work_data$weight_group)
LRT <- 2*(logLik(interaction.model) - logLik(additive.model))
LRT
round(pchisq(as.numeric(LRT), 2, lower.tail = FALSE),3)
```


```{r}
end_model = coxph(kap_surv ~ work_data$dec_start + work_data$weight_group*work_data$dec_start + work_data$height_group + work_data$weight_group)
cox.zph(end_model)
summary(end_model)
```

hazard ratios
```{r}
#install.packages("survminer")
library(survminer)
haz1 = ggforest(end_model, data = work_data, main = "Hazard Ratio")
haz1

exp(confint(end_model))
```

extension 1 aft model
```{r}
aft_mod = survfit(kap_surv ~ work_data$dec_start)
plot(log(aft_mod$time[1:10]), log(aft_mod$surv[1:10]/(1 - aft_mod$surv[1:10])))
aft_mod = survfit(kap_surv ~ work_data$height_group)
plot(log(aft_mod$time[1:10]), log(aft_mod$surv[1:10]/(1 - aft_mod$surv[1:10])))
aft_mod = survfit(kap_surv ~ work_data$weight_group)
plot(log(aft_mod$time[1:10]), log(aft_mod$surv[1:10]/(1 - aft_mod$surv[1:10])))

loglig = survreg(formula = kap_surv ~ work_data$dec_start + work_data$height_group + work_data$weight_group, dist = "loglogistic")
summary(loglig)
```
